language: node_js
node_js:
  - "10"
stages:
  - test
  - publish
jobs:
  include:
  - stage: test
    script: npm run test
  - stage: publish
    script: npm version prerelease --preid=beta && cp .template.npmrc $HOME/.npmrc && npm run build && npm publish --tag beta
    if: branch = development
  - stage: publish
    script: npm version patch && cp .template.npmrc $HOME/.npmrc && npm run build && npm publish --tag beta
    if: branch = master
